// <auto-generated />
using System;
using EsportHub.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EsportHub.Persistence.Migrations
{
    [DbContext(typeof(EsportHubDbContext))]
    [Migration("20260615165723_RemoveUniqueIndexOnGroupTeamStandingPosition")]
    partial class RemoveUniqueIndexOnGroupTeamStandingPosition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EsportHub.Domain.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Team1Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Team1Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("Team2Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Team2Score")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Team1Id");

                    b.HasIndex("Team2Id");

                    b.ToTable("Matches", t =>
                        {
                            t.HasCheckConstraint("CK_Matches_ScorePairConsistency", "(\"Team1Score\" IS NULL AND \"Team2Score\" IS NULL) OR (\"Team1Score\" IS NOT NULL AND \"Team2Score\" IS NOT NULL)");
                        });

                    b.HasDiscriminator<string>("StageType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EsportHub.Domain.Teams.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("EsportHub.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("EsportHub.Domain.Tournaments.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupStageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupStageId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("EsportHub.Domain.Tournaments.GroupStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId")
                        .IsUnique();

                    b.ToTable("GroupStages");
                });

            modelBuilder.Entity("EsportHub.Domain.Tournaments.GroupTeamStanding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("PointsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("PointsFor")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.HasIndex("GroupId", "TeamId")
                        .IsUnique();

                    b.ToTable("GroupTeamStandings");
                });

            modelBuilder.Entity("EsportHub.Domain.Tournaments.KnockoutStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId")
                        .IsUnique();

                    b.ToTable("KnockoutStages");
                });

            modelBuilder.Entity("EsportHub.Domain.Tournaments.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("EsportHub.Domain.Matches.GroupStageMatch", b =>
                {
                    b.HasBaseType("EsportHub.Domain.Matches.Match");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.HasIndex("GroupId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Matches_ScorePairConsistency", "(\"Team1Score\" IS NULL AND \"Team2Score\" IS NULL) OR (\"Team1Score\" IS NOT NULL AND \"Team2Score\" IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("Group");
                });

            modelBuilder.Entity("EsportHub.Domain.Matches.KnockoutStageMatch", b =>
                {
                    b.HasBaseType("EsportHub.Domain.Matches.Match");

                    b.Property<Guid>("KnockoutStageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Side")
                        .HasColumnType("text");

                    b.HasIndex("KnockoutStageId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Matches_ScorePairConsistency", "(\"Team1Score\" IS NULL AND \"Team2Score\" IS NULL) OR (\"Team1Score\" IS NOT NULL AND \"Team2Score\" IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("Knockout");
                });

            modelBuilder.Entity("EsportHub.Domain.Matches.Match", b =>
                {
                    b.HasOne("EsportHub.Domain.Teams.Team", "Team1")
                        .WithMany()
                        .HasForeignKey("Team1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EsportHub.Domain.Teams.Team", "Team2")
                        .WithMany()
                        .HasForeignKey("Team2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team1");

                    b.Navigation("Team2");
                });

            modelBuilder.Entity("EsportHub.Domain.Teams.Player", b =>
                {
                    b.HasOne("EsportHub.Domain.Teams.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EsportHub.Domain.Teams.Team", b =>
                {
                    b.HasOne("EsportHub.Domain.Tournaments.Group", null)
                        .WithMany("Teams")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EsportHub.Domain.Tournaments.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("EsportHub.Domain.Tournaments.Group", b =>
                {
                    b.HasOne("EsportHub.Domain.Tournaments.GroupStage", "GroupStage")
                        .WithMany("Groups")
                        .HasForeignKey("GroupStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupStage");
                });

            modelBuilder.Entity("EsportHub.Domain.Tournaments.GroupStage", b =>
                {
                    b.HasOne("EsportHub.Domain.Tournaments.Tournament", "Tournament")
                        .WithOne("GroupStage")
                        .HasForeignKey("EsportHub.Domain.Tournaments.GroupStage", "TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("EsportHub.Domain.Tournaments.GroupTeamStanding", b =>
                {
                    b.HasOne("EsportHub.Domain.Tournaments.Group", "Group")
                        .WithMany("Standings")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EsportHub.Domain.Teams.Team", "Team")
                        .WithOne()
                        .HasForeignKey("EsportHub.Domain.Tournaments.GroupTeamStanding", "TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EsportHub.Domain.Tournaments.KnockoutStage", b =>
                {
                    b.HasOne("EsportHub.Domain.Tournaments.Tournament", "Tournament")
                        .WithOne("KnockoutStage")
                        .HasForeignKey("EsportHub.Domain.Tournaments.KnockoutStage", "TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("EsportHub.Domain.Matches.GroupStageMatch", b =>
                {
                    b.HasOne("EsportHub.Domain.Tournaments.Group", "Group")
                        .WithMany("Matches")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("EsportHub.Domain.Matches.KnockoutStageMatch", b =>
                {
                    b.HasOne("EsportHub.Domain.Tournaments.KnockoutStage", "KnockoutStage")
                        .WithMany("Matches")
                        .HasForeignKey("KnockoutStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KnockoutStage");
                });

            modelBuilder.Entity("EsportHub.Domain.Teams.Team", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("EsportHub.Domain.Tournaments.Group", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Standings");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("EsportHub.Domain.Tournaments.GroupStage", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("EsportHub.Domain.Tournaments.KnockoutStage", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("EsportHub.Domain.Tournaments.Tournament", b =>
                {
                    b.Navigation("GroupStage");

                    b.Navigation("KnockoutStage");
                });
#pragma warning restore 612, 618
        }
    }
}
