name: CI base

on:
  workflow_call:

jobs:
  ci_base:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          cache: true
          cache-dependency-path: EsportHub.Backend/EsportHub.Backend.slnx
      
      - name: Install dependencies
        run: dotnet restore EsportHub.Backend/EsportHub.Backend.slnx
      
      - name: Lint
        run: dotnet format EsportHub.Backend/EsportHub.Backend.slnx --verify-no-changes --no-restore
      
      - name: Build
        run: dotnet build EsportHub.Backend/EsportHub.Backend.slnx --no-restore
      
      - name: Run tests
        run: dotnet test EsportHub.Backend/EsportHub.Backend.slnx --no-build
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Build development image without push
        uses: docker/build-push-action@v7
        with:
          context: EsportHub.Backend
          file: EsportHub.Backend/Dockerfile.dev
          push: false # Only check if build succeeds and ignore build result
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build production image without push
        uses: docker/build-push-action@v7
        with:
          context: EsportHub.Backend
          file: EsportHub.Backend/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
